# Generated by Django 5.2.5 on 2025-08-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_cliente_options_alter_membresia_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={
                "ordering": ["-fecha_registro"],
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.AlterModelOptions(
            name="membresia",
            options={
                "ordering": ["-fecha_inicio"],
                "verbose_name": "Membresía",
                "verbose_name_plural": "Membresías",
            },
        ),
        migrations.AlterModelOptions(
            name="pago",
            options={
                "ordering": ["-fecha_pago"],
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
            },
        ),
        migrations.AlterModelOptions(
            name="plan",
            options={
                "ordering": ["precio"],
                "verbose_name": "Plan",
                "verbose_name_plural": "Planes",
            },
        ),
        migrations.RemoveIndex(
            model_name="cliente",
            name="core_client_email_3bd91c_idx",
        ),
        migrations.RemoveIndex(
            model_name="cliente",
            name="core_client_fecha_r_75d495_idx",
        ),
        migrations.AlterField(
            model_name="pago",
            name="estado",
            field=models.CharField(
                choices=[("pendiente", "Pendiente"), ("pagado", "Pagado")],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="metodo_pago",
            field=models.CharField(
                choices=[("efectivo", "Efectivo"), ("tarjeta", "Tarjeta")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                help_text=(
                    "ID único de la transacción "
                    "(ej: generado por el banco o sistema)"
                ),
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="duracion_dias",
            field=models.PositiveIntegerField(help_text="Duración en días"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="precio",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name="cliente",
            table="clientes",
        ),
        migrations.AlterModelTable(
            name="membresia",
            table="membresias",
        ),
        migrations.AlterModelTable(
            name="pago",
            table="pagos",
        ),
        migrations.AlterModelTable(
            name="plan",
            table="planes",
        ),
    ]
