# Generated by Django 5.2.5 on 2025-08-25 01:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "duracion_dias",
                    models.PositiveIntegerField(help_text="Duración en días"),
                ),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Planes",
                "db_table": "planes",
                "ordering": ["precio"],
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "fecha_registro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cliente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "clientes",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="Membresia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(default=django.utils.timezone.now)),
                ("fecha_fin", models.DateField()),
                ("activa", models.BooleanField(default=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membresias",
                        to="core.cliente",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membresias",
                        to="core.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membresía",
                "verbose_name_plural": "Membresías",
                "db_table": "membresias",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_pago", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[("efectivo", "Efectivo"), ("tarjeta", "Tarjeta")],
                        max_length=50,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("pendiente", "Pendiente"), ("pagado", "Pagado")],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="core.cliente",
                    ),
                ),
                (
                    "membresia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagos",
                        to="core.membresia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "db_table": "pagos",
                "ordering": ["-fecha_pago"],
            },
        ),
        migrations.AddIndex(
            model_name="membresia",
            index=models.Index(fields=["cliente", "plan"], name="idx_cliente_plan"),
        ),
        migrations.AddConstraint(
            model_name="membresia",
            constraint=models.CheckConstraint(
                condition=models.Q(("fecha_fin__gte", models.F("fecha_inicio"))),
                name="fecha_fin_mayor_inicio",
            ),
        ),
        migrations.AddConstraint(
            model_name="membresia",
            constraint=models.UniqueConstraint(
                fields=("cliente", "plan", "fecha_inicio"),
                name="unique_membresia_cliente_plan_fecha_inicio",
            ),
        ),
    ]
