# Generated by Django 5.2.5 on 2025-08-25 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={"ordering": ["-fecha_registro"]},
        ),
        migrations.AlterModelOptions(
            name="membresia",
            options={"ordering": ["-fecha_inicio"]},
        ),
        migrations.AlterModelOptions(
            name="pago",
            options={"ordering": ["-fecha_pago"]},
        ),
        migrations.AlterModelOptions(
            name="plan",
            options={"ordering": ["nombre"]},
        ),
        migrations.AddField(
            model_name="pago",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="membresia",
            name="fecha_fin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pago",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("pagado", "Pagado"),
                    ("fallido", "Fallido"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="metodo_pago",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("tarjeta", "Tarjeta"),
                    ("transferencia", "Transferencia"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="descripcion",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="plan",
            name="duracion_dias",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="plan",
            name="precio",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["email"],
                name="core_client_email_3bd91c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["fecha_registro"],
                name="core_client_fecha_r_75d495_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pago",
            index=models.Index(
                fields=["cliente"],
                name="idx_pago_cliente",
            ),
        ),
        migrations.AddIndex(
            model_name="pago",
            index=models.Index(
                fields=["transaction_id"],
                name="idx_pago_tx",
            ),
        ),
        migrations.AddConstraint(
            model_name="pago",
            constraint=models.CheckConstraint(
                condition=models.Q(("monto__gte", 0)),
                name="monto_non_negative",
            ),
        ),
        migrations.AlterModelTable(
            name="cliente",
            table=None,
        ),
        migrations.AlterModelTable(
            name="membresia",
            table=None,
        ),
        migrations.AlterModelTable(
            name="pago",
            table=None,
        ),
        migrations.AlterModelTable(
            name="plan",
            table=None,
        ),
    ]
